[package]
name = "cargo-find-target"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/burbokop/conf_plugin"

[dependencies]
serde = { version = "1.0.136", features = ["derive"] }
regex = "1"
clap = { version = "3.1.5", features = ["derive"] }
